### ISSUE TITLE
Not a directory

### ISSUE THREAD

**Issue by jelic98** [koallen/google-image-downloader#2] opened 2017-06-28 22:38 UTC
Traceback (most recent call last):
  File "download_images.py", line 74, in <module>
    source = search(url)
  File "download_images.py", line 15, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory

**Comment by koallen** [comment] 2017-06-29 02:44
Hi, this repo is not actively maintained as of now.

Judging from your traceback, it seems that you changed chrome to firefox. I've not tested this with firefox personally. The error happens when opening the browser. Maybe you didn't configure the web driver properly (I remember I have to do something for chrome to work).

**Comment by koallen** [comment] 2017-07-05 15:52
Closing for now, feel free to reopen if the problem is not fixed.

**Closed by koallen** 2017-07-05 15:52 UTC
